version: "3.7"
services:
  mongo:
    build: .
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27017:27017"
    restart: always
  mongo_express:
    image: mongo-express
    container_name: mongo_express
    depends_on:
      - "mongo"
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
    restart: always
